### ISSUE TITLE
Setup testing framework and improve type checking

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/zbd-node#1]
## Tasks

- Introduce testing framework/tools (e.g. `jest`) to facilitate the writing of unit tests for the many API endpoints in the SDK.
  - Setup file structure and provide initial testing cases for a handful of endpoints
- Improve type checking to properly match `docs.zebedee.io/api`
  - There are too many `any` types at the moment)
  - Properly segregate types into separate files

**Comment by haruncurak** [comment]
/attempt #1 

gonna start working on this one.

**Comment by andrerfneves** [comment]
Amazing!

**Comment by haruncurak** [comment]
Since accessing the API endpoints requires an API key, I think it would be easiest if we had a key specifically for the purposes of testing - would it be possible to create one with the appropriate permissions? Should I just create one with my own zebedee dev account?

**Comment by andrerfneves** [comment]
Hey @haruncurak that's perfectly fine. I've created this one for you: `8qJxln3JVJsQM0IOJhfnJopO0JSiLdlK`. Let me know if you need access to the full dashboard.

**Comment by haruncurak** [comment]
@andrerfneves Hi - any updates on this issue?

**Comment by andrerfneves** [comment]
@haruncurak so sorry about the delay here. Going to review and figure payout tomorrow 🫡

**Comment by andrerfneves** [comment]
Thank you thank you 👍
