### ISSUE TITLE
Increase testing coverage for SDK endpoints

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/zbd-node#2]
## Tasks

- Following on #1, use the newly-defined library testing suite to write tests for each of the API endpoints in this SDK
- Tests need to be thorough and cover all paths/cases

**Comment by haruncurak** [comment]
I'll get on this once I'm done with #1 !
/attempt 2

**Comment by andrerfneves** [comment]
Getting to 100% coverage would be splendid.

**Comment by andrerfneves** [comment]
hey @haruncurak how goes here? Anything i can help with?

**Comment by haruncurak** [comment]
Hey @andrerfneves, it's taking quite a bit more work than I thought. Almost there though!

**Comment by haruncurak** [comment]
Hi @andrerfneves, it would be awesome if you could provide me with another API key to test sending/receiving/withdrawing as thoroughly as possible. Everything else is done, feel free to check out my repo.

**Comment by andrerfneves** [comment]
For sure! @haruncurak other key here: `dESXgwgy7GziAbVA7AyN56uATloaburz`

**Comment by haruncurak** [comment]
Awesome, thanks @andrerfneves ! I need one last thing: if you can either give me dash access for the first API key or create another project for that user, so that I can write one final testcase for internal transfers. 

Otherwise everything is done.

**Comment by andrerfneves** [comment]
Hey @haruncurak I saw you created an account. Going to approve your user so you can get LIVE API Keys and then do this testing. Bear with me

**Comment by andrerfneves** [comment]
@haruncurak you're all set. Make sure to create two projects and use the LIVE key for them.

**Comment by haruncurak** [comment]
Great! I don't think I can test internal transfers since I don't have any money in either of the projects though, right? @andrerfneves

**Comment by andrerfneves** [comment]
@haruncurak use this Voucher code inside of the VOUCHERS section, and then use this voucher: `4B88E9DB` to redeem some sats. And then use CMD + K (quick actions) to TRANSFER to your project wallet.

**Comment by haruncurak** [comment]
Should be a wrap @andrerfneves, let me know if you need anything else!

**Comment by andrerfneves** [comment]
Amazing!! @haruncurak I will have time to review this later today and tomorrow. Hopefully it's all good and I can award asap. Thanks for the work on this. Bear w me

**Comment by haruncurak** [comment]
Hey @andrerfneves , just checking back in on this : )

**Comment by andrerfneves** [comment]
Thank you!
