### ISSUE TITLE
Create NextAuth.js Starter Kit with ZBD Login

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/zbd-node#3]
## Tasks

- Create a `zebedee-nextauth-starter` open source repo that is a full-blown example of using `next-auth` with the `zbd login` OAuth2 functionality from the ZEBEDEE API
- The example code should handle the full PKCE + Authorization flow pointed to `accounts.zebedee.io`

### Resources

- https://next-auth.js.org/v3/configuration/providers
- https://next-auth.js.org/
- https://github.com/nextauthjs/next-auth-example
- https://docs.zebedee.io/api

**Comment by andrerfneves** [comment]
Let me know if something isn’t clear @dylanrod21!

**Comment by dylanrod21** [comment]
Hi, I spent a bit of time on this last night, I haven't setup a custom provider before with NextAuth.js and was having running into a couple issues, Ill take another look later today after work. I just set the repo to public, all I did was copy the next-auth-example repo and make some changes to the auth route to begin setting up a custom provider for login. I've only setup google as a provider in the past so one thing that wasn't clear to me was where to get the clientId for zebedee. 

https://github.com/dylanrod21/zebedee-nextauth-starter

**Comment by andrerfneves** [comment]
Sounds awesome @dylanrod21. Lmk if you need help/input. We have a few open source repo examples on using it with Passport for example.

**Comment by rishi-raj-jain** [comment]
@andrerfneves Can I work on this one?

**Comment by andrerfneves** [comment]
Seeing as @dylanrod21 hasn't given updates here in 2+ weeks, and no code has been pushed, I'm going to go ahead and say that YES @rishi-raj-jain pls take this one on 😃

**Comment by rishi-raj-jain** [comment]
@andrerfneves 

Can you share some examples of the same?

**Comment by rishi-raj-jain** [comment]
Also, as I see it, the clientID and clientSecret are two random variables set be the user, right?

**Comment by rishi-raj-jain** [comment]
@andrerfneves Did you get a chance to look at my comment?

**Comment by rishi-raj-jain** [comment]
@andrerfneves Did you get a chance to look at my comment?

**Comment by andrerfneves** [comment]
@dylanrod21 has not pushed any code is over 3 weeks. @rishi-raj-jain this one is yours to take. Let me get you the creds necessary.

**Comment by andrerfneves** [comment]
@rishi-raj-jain best way would be to give you access to an account on the dashboard. What best way to contact you to send you an invite code? Followed you on Twitter so I can DM it to you but couldnt DM.

**Comment by rishi-raj-jain** [comment]
@andrerfneves I just Twitter DM'd you.

**Comment by rishi-raj-jain** [comment]
Hey @andrerfneves,

Would love to collaborate on this/

**Comment by rishi-raj-jain** [comment]
Hey @andrerfneves,

Would love to collaborate on this.

**Comment by andrerfneves** [comment]
Hey @rishi-raj-jain after we resolve the items for the API Docs, we can tackle this one. You can use the clientID and clientSecrets from this comment: https://github.com/zebedeeio/zbd-node/pull/6#issuecomment-1646909738 but lmk if you get blocked.

**Comment by rishi-raj-jain** [comment]
@andrerfneves 

The API Docs are resolved. Let me check that comment.

**Comment by rishi-raj-jain** [comment]
@andrerfneves

Do you have an example of pkce integration?

**Comment by rishi-raj-jain** [comment]
@andrerfneves

Do you have an example of pkce integration?

**Comment by andrerfneves** [comment]
Hey @rishi-raj-jain check out these repos:

https://github.com/zebedeeio/passport-zebedee
https://github.com/zebedeeio/login-zbd-react-native-example

**Comment by rishi-raj-jain** [comment]
@andrerfneves 

https://github.com/zebedeeio/zbd-node/pull/6#issuecomment-1678704777

**Comment by rishi-raj-jain** [comment]
@andrerfneves

https://github.com/zebedeeio/zbd-node/pull/6#issuecomment-1678704777

**Comment by rishi-raj-jain** [comment]
@andrerfneves

#6 (comment)

**Comment by rishi-raj-jain** [comment]
Hey @andrerfneves,
I tagged you in another GitHub thread regarding same. Can you help me with that so that I can complete this?

**Comment by rishi-raj-jain** [comment]
@andrerfneves Are you

**Comment by rockingrohit9639** [comment]
@andrerfneves Is this issue still active ?

**Comment by andrerfneves** [comment]
Closing this in favor of a new bounty with a better setup

**Comment by andrerfneves** [comment]
@rockingrohit9639 https://github.com/zebedeeio/next-auth-zbd-starter/issues/1

**Comment by rishi-raj-jain** [comment]
@andrerfneves as you saw, I spent most of the time on it I'm working on it atm.

**Comment by rishi-raj-jain** [comment]
I request to assign the issue to me please!

**Comment by andrerfneves** [comment]
That's fine @rishi-raj-jain. Let's get this thing working and I'm happy to award this to you no problem.
